#!/bin/sh

set -e

case "$1" in
	purge)
	rm /etc/monit/conf.d/yunohost-includes/alert
	rm /etc/monit/conf.d/yunohost-includes/mailserver
	;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
